export type GrowStatus = 'Planning' | 'Running' | 'Completed' | 'Aborted'
export type GrowStage = 'Seedling' | 'Clone' | 'Veg' | 'Transition' | 'Flower' | 'Finish' | 'Dry' | 'Cure'
export type ValueOrigin = 'Manual' | 'HomeAssistant' | 'Imported' | 'Derived'
export type TaskPriority = 'Low' | 'Normal' | 'High' | 'Critical'
export type GrowTaskStatus = 'Open' | 'Done' | 'Skipped'
export type SopInstanceStatus = 'Active' | 'Completed' | 'Cancelled'
export type SopStepInstanceStatus = 'Pending' | 'InProgress' | 'Done' | 'Skipped'
export type SopStartSource = 'Manual' | 'Recommendation' | 'System'
export type HydroStyle = 'None' | 'DWC' | 'RDWC' | 'NFT' | 'Aeroponic' | 'Other'
export type SelectableHydroStyle = 'DWC' | 'RDWC'
export type HydroSetupStatus = 'Active' | 'Archived'
export type HydroSetupLayoutType = 'SingleBucket' | 'Row' | 'Grid2x2' | 'Grid2x3' | 'Grid2x4' | 'Custom'
export type ReservoirPosition = 'None' | 'Left' | 'Right' | 'Top' | 'Bottom' | 'External'
export type GrowEnvironment = 'Indoor' | 'Outdoor' | 'Greenhouse'
export type SeedType = 'Feminized' | 'Autoflower' | 'Regular'
export type StartMaterial = 'Seed' | 'Clone'
export type JournalEntryType = 'Note' | 'Observation' | 'Action' | 'Problem' | 'Solution' | 'Training' | 'Transplant' | 'Feeding' | 'ReservoirChange' | 'GerminationConfirmed' | 'CloneRooted' | 'FlipToFlower' | 'VegStarted' | 'FinishStarted'
export type WaterSource = 'Tap' | 'RO' | 'Mixed'
export type GrowEntryPoint = 'Germination' | 'Seedling' | 'Veg' | 'Flower' | 'Flush'
/** Phase laut Phasenanker (Backend `Ankerphase`). */
export type Ankerphase = 'Anzucht' | 'Veg' | 'Uebergang' | 'Bluete' | 'Finish' | 'Ende'
/** Was in der Anzucht gerade passiert (Backend `Anzuchtart`). */
export type Anzuchtart = 'Keimung' | 'Saemling' | 'Bewurzelung'
export type GerminationMethod = 'PaperTowel' | 'Rockwool' | 'RapidRooter' | 'DirectInSystem'
export type PropagationMedium = 'Rockwool' | 'Hydroton' | 'RapidRooter' | 'Neoprene'
export type PhotoTag = 'Overview' | 'Canopy' | 'Leaf' | 'Root' | 'Training' | 'Flower' | 'Problem' | 'Comparison' | 'Other'
export type SetupType = 'Production' | 'Mother' | 'Quarantine' | 'Propagation'
export type SetupStatus = 'Planning' | 'Active' | 'Archived'
export type MotherHealthStatus = 'Stable' | 'Watch' | 'Critical'
export type QuarantineResult = 'Pending' | 'Cleared' | 'Rejected'
export type PlantRole = 'Production' | 'Mother' | 'Clone' | 'Quarantine'
export type PlantStatus = 'Planned' | 'Active' | 'Archived' | 'Culled' | 'Harvested'
export type StrainDominance = 'Unknown' | 'Indica' | 'Sativa' | 'Hybrid'
export type AutoMeasurementStatus = 'Enabled' | 'Disabled'
export type AutoMeasurementAggregation = 'Latest' | 'Median' | 'Average'
export type AutoMeasurementField =
  | 'AirTemperatureC'
  | 'HumidityPercent'
  | 'ReservoirPh'
  | 'ReservoirEc'
  | 'ReservoirWaterTempC'
  | 'ReservoirLevelLiters'
  | 'ReservoirLevelCm'
  | 'DissolvedOxygenMgL'
  | 'OrpMv'
  | 'PpfdMol'
  | 'Co2Ppm'
export type AutoMeasurementTriggerKind = 'Manual' | 'LightOnDelay' | 'LightOffDelay'
export type AutoMeasurementRunStatus = 'Pending' | 'Created' | 'Skipped' | 'Failed'
export type DeviationMetric = 'Ph' | 'Ec' | 'Orp' | 'WaterTemp' | 'Vpd' | 'Ppfd' | 'Co2' | 'DissolvedOxygen' | 'GerminationStatus'
export type DeviationSeverity = 'Info' | 'Warning' | 'Critical'
export type DeviationSource = 'Manual' | 'HomeAssistant' | 'Mixed' | 'Unknown'
export type TreatmentRecommendationConfidence = 'Low' | 'Medium' | 'High'
export type HardwareItemStatus = 'Active' | 'MaintenanceDue' | 'Offline' | 'Retired'
export type HardwareItemCriticality = 'Low' | 'Medium' | 'High' | 'Critical'
export type MaintenanceEventType = 'Inspection' | 'Cleaning' | 'Replacement' | 'Repair' | 'Other'
export type MaintenanceEventStatus = 'Planned' | 'Completed' | 'Skipped' | 'Cancelled'
export type MaintenanceResult = 'Unknown' | 'Passed' | 'ActionNeeded' | 'Replaced' | 'Failed'
export type CalibrationEventType = 'Ph' | 'Ec' | 'Orp' | 'Do' | 'Other'
export type CalibrationEventStatus = 'Planned' | 'Completed' | 'Failed' | 'Skipped' | 'Cancelled'
export type CalibrationResult = 'Unknown' | 'Passed' | 'AdjustmentNeeded' | 'Failed'
export type RiskEventType = 'PowerOutage' | 'UpsOnBattery' | 'PumpOffline' | 'ChillerOffline' | 'LightMismatch' | 'HomeAssistantUnavailable' | 'CriticalDo' | 'SensorUnavailable' | 'Other'
export type RiskEventSeverity = 'Info' | 'Warning' | 'Critical'
export type RiskEventStatus = 'Open' | 'Acknowledged' | 'Resolved' | 'Ignored'
export type RiskEventSource = 'Manual' | 'HomeAssistant' | 'AutoMeasurement' | 'Deviation' | 'System'

export interface ApiError {
  code: string
  message: string
  fieldErrors?: Record<string, string[]>
}
